CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "cpf" varchar(14) UNIQUE NOT NULL,
  "telefone" varchar(20),
  "email" varchar(100),
  "endereco" varchar(150)
);

CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "login" varchar(50) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL
);

CREATE TABLE "veiculo" (
  "id_veiculo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int NOT NULL,
  "placa" varchar(10) UNIQUE NOT NULL,
  "marca" varchar(50),
  "modelo" varchar(50),
  "ano" int
);

CREATE TABLE "ordem_servico" (
  "id_os" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_veiculo" int NOT NULL,
  "id_usuario" int NOT NULL,
  "data_abertura" date NOT NULL,
  "data_fechamento" date,
  "descricao" text,
  "status" varchar(30) NOT NULL,
  "valor" decimal(10,2)
);

ALTER TABLE "veiculo" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ordem_servico" ADD FOREIGN KEY ("id_veiculo") REFERENCES "veiculo" ("id_veiculo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ordem_servico" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
